name: Build
on:
  push:
    tags: ["v*"]
    branches: ["main"]
  pull_request:
    branches: ["*"]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    env:
      LLVM_BIN: /usr/lib/llvm-13/bin
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: '17'
          cache: sbt

      - name: Cache vcpkg
        uses: actions/cache@v3
        with:
          path: |
            ~/Library/Caches/sbt-vcpkg/vcpkg
            ~/.cache/sbt-vcpkg/vcpkg
            ~/.cache/sbt-vcpkg/vcpkg-install
          key: ${{ runner.os }}-sbt-vcpkg-new
          
      - uses: rui314/setup-mold@v1

      - name: Install Nginx Unit
        shell: bash
        run: 
          sudo curl --output /usr/share/keyrings/nginx-keyring.gpg https://unit.nginx.org/keys/nginx-keyring.gpg

          sudo sh -c 'echo "deb [signed-by=/usr/share/keyrings/nginx-keyring.gpg] https://packages.nginx.org/unit/ubuntu/ focal unit" >> /etc/apt/sources.list.d/unit.list'

          sudo sh -c 'echo "deb-src [signed-by=/usr/share/keyrings/nginx-keyring.gpg] https://packages.nginx.org/unit/ubuntu/ focal unit" >> /etc/apt/sources.list.d/unit.list'

          sudo apt update

          sudo apt install unit unit-dev

          sudo systemctl restart unit

      - name: Setup Postgres
        run: |
          set -e
          docker run -p 5432:5432 -e POSTGRES_PASSWORD=mysecretpassword -d postgres

      - name: Setup for Scala Native
        run: sudo ./scripts/setup-debian.sh

      - name: Start application
        run: sbt buildApp test
        env:
          USE_SUDO: true

      - name: Integration tests 
        run: curl http://localhost:8080/api/health

      - name: Print logs
        if: failure()
        run: 
          sudo cat /var/log/unit.log

          echo $PWD

          ls -la build


  docker_build:
    name: Docker build
    runs-on: ubuntu-20.04
    if: "!(startsWith(github.ref, 'refs/tags/v') || (github.ref == 'refs/heads/main'))"
    steps:
      - uses: actions/checkout@v3

      - name: Docker build
        run: docker build . -t twotm8

  mergify_build_summary:
    name: Build summary
    runs-on: ubuntu-latest
    needs: [build, docker_build]
    steps:
      - name: I only exist to please Mergify :(
        run: echo "It's a sad existence but necessary"

  deploy:
    name: Deploy
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/v') || (github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
        with:
          fetch-depth: 0

      - uses: superfly/flyctl-actions@master
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        with:
          args: "deploy"
