name: Build
on:
  push:
    tags: ["v*"]
    branches: ["main"]
  pull_request:
    branches: ["*"]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    env:
      LLVM_BIN: /usr/lib/llvm-13/bin
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: '17'
          cache: sbt

      - name: Cache vcpkg
        uses: actions/cache@v3
        with:
          path: |
            ~/Library/Caches/sbt-vcpkg/vcpkg
            ~/.cache/sbt-vcpkg/vcpkg
            ~/.cache/sbt-vcpkg/vcpkg-install
          key: ${{ runner.os }}-sbt-vcpkg-new
          
      - uses: rui314/setup-mold@v1

      - name: Setup Postgres
        run: |
          set -e
          docker run -p 5432:5432 -e POSTGRES_PASSWORD=mysecretpassword -d postgres

      - name: Setup for Scala Native
        run: sudo ./scripts/setup-debian.sh

      - name: Build app
        run: sbt buildApp

      - name: Start service in docker
        run: |
          docker build -f Dockerfile.lean . -t twotm8-runtime
          mkdir -p logs
          docker run -d -v $PWD/logs:/var/log -e JWT_SECRET=secret --network host twotm8-runtime 

      - name: Integration tests 
        run: sbt integrationTests
        env:
          TWOTM8_URL: http://localhost:8080

      - name: Print logs
        if: failure()
        shell: bash
        run: |
          sudo cat logs/*.log

  mergify_build_summary:
    name: Build summary
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: I only exist to please Mergify :(
        run: echo "It's a sad existence but necessary"

  deploy-staging:
    name: Deploy staging
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/v') || (github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: '17'
          cache: sbt

      - uses: superfly/flyctl-actions@master

      - name: Deploy to fly.io
        run: flyctl deploy -c fly-staging.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: End to end tests  
        run: sbt integrationTests 
        env:
          TWOTM8_URL: https://twotm8-web-staging.fly.dev

  deploy-production:
    name: Deploy production
    needs: [build, deploy-staging]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
        with:
          fetch-depth: 0

      - uses: superfly/flyctl-actions@master

      - name: Deploy to fly.io
        run: flyctl deploy -c fly-production.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
